services:
  Mollie\Builder\LegacyTranslatorAwareType:
    class: Mollie\Builder\LegacyTranslatorAwareType
    arguments:
      - '@Mollie\Service\LegacyTranslator'

  Mollie\Form\Admin\Credentials\Type\LegacyCredentialsType:
    class: Mollie\Form\Admin\Credentials\Type\LegacyCredentialsType
    parent: Mollie\Builder\LegacyTranslatorAwareType
    calls:
      - [ setModule, [ '@mollie' ] ]
    tags:
      - { name: mollie.form.type }

  Mollie\Form\Admin\GeneralSettings\Type\LegacyGeneralSettingsType:
    class: Mollie\Form\Admin\GeneralSettings\Type\LegacyGeneralSettingsType
    parent: Mollie\Builder\LegacyTranslatorAwareType
    calls:
      - [ setModule, [ '@mollie' ] ]
    tags:
      - { name: mollie.form.type }

  Mollie\Form\Admin\AdvancedSettings\Type\LegacyAdvancedSettingsType:
    class: Mollie\Form\Admin\AdvancedSettings\Type\LegacyAdvancedSettingsType
    parent: Mollie\Builder\LegacyTranslatorAwareType
    calls:
      - [ setModule, [ '@mollie' ] ]
    tags:
      - { name: mollie.form.type }

  Mollie\Form\Admin\GeneralSettings\Type\LegacyPaymentMethodType:
    class: Mollie\Form\Admin\GeneralSettings\Type\LegacyPaymentMethodType
    parent: Mollie\Builder\LegacyTranslatorAwareType
    calls:
      - [ setModule, [ '@mollie' ] ]
      - [ setApiService, [ '@Mollie\Service\ApiService' ] ]
      - [ setCountryService, [ '@Mollie\Service\CountryService' ] ]
      - [ setCreditCardLogoProvider, [ '@Mollie\Provider\CreditCardLogoProvider' ] ]
    tags:
      - { name: mollie.form.general.settings.type }

  Mollie\Form\Admin\AdvancedSettings\Type\LegacyMailSettingsType:
    class: Mollie\Form\Admin\AdvancedSettings\Type\LegacyMailSettingsType
    parent: Mollie\Builder\LegacyTranslatorAwareType
    calls:
      - [ setModule, [ '@mollie' ] ]
    tags:
      - { name: mollie.form.advanced.settings.type }

  Mollie\Form\Admin\AdvancedSettings\Type\LegacyOrderStatusesSettingsType:
    class: Mollie\Form\Admin\AdvancedSettings\Type\LegacyOrderStatusesSettingsType
    parent: Mollie\Builder\LegacyTranslatorAwareType
    calls:
      - [ setModule, [ '@mollie' ] ]
      - [ setContext, [ '@=service("mollie.adapter.context")' ] ]
    tags:
      - { name: mollie.form.advanced.settings.type }

  Mollie\Form\Admin\AdvancedSettings\Type\LegacyVisualSettingsType:
    class: Mollie\Form\Admin\AdvancedSettings\Type\LegacyVisualSettingsType
    parent: Mollie\Builder\LegacyTranslatorAwareType
    calls:
      - [ setModule, [ '@mollie' ] ]
    tags:
      - { name: mollie.form.advanced.settings.type }

  Mollie\Form\Admin\AdvancedSettings\Type\LegacyShipmentSettingsType:
    class: Mollie\Form\Admin\AdvancedSettings\Type\LegacyShipmentSettingsType
    parent: Mollie\Builder\LegacyTranslatorAwareType
    calls:
      - [ setModule, [ '@mollie' ] ]
      - [ setContext, [ '@=service("mollie.adapter.context")' ] ]
      - [ setCarrierInformationService, [ '@Mollie\Service\MolCarrierInformationService' ] ]
    tags:
      - { name: mollie.form.advanced.settings.type }

  Mollie\Form\Admin\AdvancedSettings\Type\LegacyDebugSettingsType:
    class: Mollie\Form\Admin\AdvancedSettings\Type\LegacyDebugSettingsType
    parent: Mollie\Builder\LegacyTranslatorAwareType
    calls:
      - [ setModule, [ '@mollie' ] ]
      - [ setContext, [ '@=service("mollie.adapter.context")' ] ]
    tags:
      - { name: mollie.form.advanced.settings.type }