services:
  Mollie\Builder\ApiTestFeedbackBuilder:
    arguments:
      - '@=service("mollie.factory.module_factory").getModuleVersion()'
      - '@Mollie\Service\ApiKeyService'

  Mollie\Builder\InvoicePdfTemplateBuilder:
    arguments:
      - '@Mollie\Repository\OrderFeeRepository'

  Mollie\Builder\Content\BaseInfoBlock:
    class: Mollie\Builder\Content\BaseInfoBlock
    arguments:
      - '@mollie'

  Mollie\Builder\Content\RoundingModeInfoBlock:
    class: Mollie\Builder\Content\RoundingModeInfoBlock
    arguments:
      - '@mollie'

  Mollie\Builder\Content\SmartyCacheInfoBlock:
    class: Mollie\Builder\Content\SmartyCacheInfoBlock
    arguments:
      - '@mollie'

  Mollie\Builder\Content\SmartyForceCompileInfoBlock:
    class: Mollie\Builder\Content\SmartyForceCompileInfoBlock
    arguments:
      - '@mollie'

  Mollie\Builder\Content\LogoInfoBlock:
    class: Mollie\Builder\Content\LogoInfoBlock
    arguments:
      - '@mollie'

  Mollie\Builder\Content\UpdateMessageInfoBlock:
    class: Mollie\Builder\Content\UpdateMessageInfoBlock
    arguments:
      - '@mollie'
      - '@Mollie\Service\UpgradeNoticeService'
      - '@Mollie\Adapter\ConfigurationAdapter'
      - '@Mollie\Provider\UpdateMessageProvider'

  Mollie\Builder\Content\PaymentOption\IdealDropdownInfoBlock:
    class: Mollie\Builder\Content\PaymentOption\IdealDropdownInfoBlock
    arguments:
      - '@mollie'
      - '@Mollie\Service\IssuerService'

  Mollie\Builder\Form\GeneralSettingsForm\GeneralSettingsForm:
    class: Mollie\Builder\Form\GeneralSettingsForm\GeneralSettingsForm
    arguments:
      - '@mollie'
      - '@Mollie\Builder\Form\GeneralSettingsForm\PaymentMethodBlock'
    tags:
      - { name: mollie.controller.form }

  Mollie\Builder\Form\AdvancedSettingsForm\AdvancedSettingsForm:
    class: Mollie\Builder\Form\AdvancedSettingsForm\AdvancedSettingsForm
    arguments:
      - '@mollie'
      - '@Mollie\Builder\Form\AdvancedSettingsForm\OrderStatusesSettingsBlock'
      - '@Mollie\Builder\Form\AdvancedSettingsForm\MailSettingsBlock'
      - '@Mollie\Builder\Form\AdvancedSettingsForm\ShipmentSettingsBlock'
      - '@Mollie\Builder\Form\AdvancedSettingsForm\VisualSettingsBlock'
      - '@Mollie\Builder\Form\AdvancedSettingsForm\DebugSettingsBlock'
    tags:
      - { name: mollie.controller.form }

  Mollie\Builder\Form\GeneralSettingsForm\PaymentMethodBlock:
    class: Mollie\Builder\Form\GeneralSettingsForm\PaymentMethodBlock
    arguments:
      - '@mollie'
      - '@Mollie\Service\ApiService'
      - '@Mollie\Service\CountryService'
      - '@Mollie\Provider\CreditCardLogoProvider'

  Mollie\Builder\Form\AdvancedSettingsForm\OrderStatusesSettingsBlock:
    class: Mollie\Builder\Form\AdvancedSettingsForm\OrderStatusesSettingsBlock
    arguments:
      - '@mollie'
      - '@=service("mollie.adapter.context")'

  Mollie\Builder\Form\AdvancedSettingsForm\MailSettingsBlock:
    class: Mollie\Builder\Form\AdvancedSettingsForm\MailSettingsBlock
    arguments:
      - '@mollie'

  Mollie\Builder\Form\AdvancedSettingsForm\ShipmentSettingsBlock:
    class: Mollie\Builder\Form\AdvancedSettingsForm\ShipmentSettingsBlock
    arguments:
      - '@mollie'
      - '@=service("mollie.adapter.context")'
      - '@Mollie\Service\MolCarrierInformationService'

  Mollie\Builder\Form\AdvancedSettingsForm\VisualSettingsBlock:
    class: Mollie\Builder\Form\AdvancedSettingsForm\VisualSettingsBlock
    arguments:
      - '@mollie'

  Mollie\Builder\Form\AdvancedSettingsForm\DebugSettingsBlock:
    class: Mollie\Builder\Form\AdvancedSettingsForm\DebugSettingsBlock
    arguments:
      - '@mollie'
      - '@=service("mollie.adapter.context")'