services:
  Mollie\Builder\FormBuilder:
    arguments:
      - '@mollie'
      - '@Mollie\Service\ApiService'
      - '@Mollie\Service\CountryService'
      - '@Mollie\Repository\CountryRepository'
      - '@Mollie\Service\ConfigFieldService'
      - '@Mollie\Service\MolCarrierInformationService'
      - '@language'
      - '@smarty'
      - '@link'
      - '@Mollie\Provider\CreditCardLogoProvider'

  Mollie\Builder\ApiTestFeedbackBuilder:
    arguments:
      - '@=service("mollie.factory.module_factory").getModuleVersion()'
      - '@Mollie\Service\ApiKeyService'

  Mollie\Builder\InvoicePdfTemplateBuilder:
    arguments:
      - '@Mollie\Repository\OrderFeeRepository'

  Mollie\Builder\Content\BaseInfoBlock:
    class: Mollie\Builder\Content\BaseInfoBlock
    arguments:
      - '@mollie'

  Mollie\Builder\Content\RoundingModeInfoBlock:
    class: Mollie\Builder\Content\RoundingModeInfoBlock
    arguments:
      - '@mollie'

  Mollie\Builder\Content\SmartyCacheInfoBlock:
    class: Mollie\Builder\Content\SmartyCacheInfoBlock
    arguments:
      - '@mollie'

  Mollie\Builder\Content\SmartyForceCompileInfoBlock:
    class: Mollie\Builder\Content\SmartyForceCompileInfoBlock
    arguments:
      - '@mollie'

  Mollie\Builder\Content\LogoInfoBlock:
    class: Mollie\Builder\Content\LogoInfoBlock
    arguments:
      - '@mollie'

  Mollie\Builder\Content\UpdateMessageInfoBlock:
    class: Mollie\Builder\Content\UpdateMessageInfoBlock
    arguments:
      - '@mollie'
      - '@Mollie\Service\UpgradeNoticeService'
      - '@Mollie\Adapter\ConfigurationAdapter'
      - '@Mollie\Provider\UpdateMessageProvider'

  Mollie\Builder\Content\PaymentOption\IdealDropdownInfoBlock:
    class: Mollie\Builder\Content\PaymentOption\IdealDropdownInfoBlock
    arguments:
      - '@mollie'
      - '@Mollie\Service\IssuerService'

  Mollie\Builder\Form\GeneralSettingsForm\GeneralSettingsForm:
    class: Mollie\Builder\Form\GeneralSettingsForm\GeneralSettingsForm
    arguments:
      - '@mollie'
      - '@Mollie\Builder\Form\GeneralSettingsForm\PaymentMethodBlock'

  Mollie\Builder\Form\CredentialsForm\CredentialsForm:
    class: Mollie\Builder\Form\CredentialsForm\CredentialsForm
    arguments:
      - '@mollie'

  Mollie\Builder\Form\GeneralSettingsForm\PaymentMethodBlock:
    class: Mollie\Builder\Form\GeneralSettingsForm\PaymentMethodBlock
    arguments:
      - '@mollie'
      - '@Mollie\Service\ApiService'
      - '@Mollie\Service\CountryService'
      - '@Mollie\Provider\CreditCardLogoProvider'
