services:
  Mollie\Service\LegacyTranslator:
    class: Mollie\Service\LegacyTranslator
    arguments:
      - '@mollie'

  Mollie\Builder\LegacyTranslatorAwareType:
    class: Mollie\Builder\LegacyTranslatorAwareType
    arguments:
      - '@Mollie\Service\LegacyTranslator'

  Mollie\Form\Admin\Credentials\Type\LegacyCredentialsType:
    class: Mollie\Form\Admin\Credentials\Type\LegacyCredentialsType
    parent: Mollie\Builder\LegacyTranslatorAwareType
    calls:
      - [ setModule, [ '@mollie' ] ]
    tags:
        - { name: mollie.form.type }

  Mollie\Form\Admin\Credentials\Type\CredentialsTypeInterface: '@Mollie\Form\Admin\Credentials\Type\LegacyCredentialsType'

  Mollie\Form\AbstractLegacyFormBuilder:
    class: Mollie\Form\AbstractLegacyFormBuilder
    arguments:
      - '@Mollie'

  Mollie\Form\Admin\Credentials\FormBuilder\LegacyCredentialsFormBuilder:
    class: Mollie\Form\Admin\Credentials\FormBuilder\LegacyCredentialsFormBuilder
    parent: Mollie\Form\AbstractLegacyFormBuilder

  Mollie\Form\Admin\Credentials\FormBuilder\CredentialsFormBuilderInterface: '@Mollie\Form\Admin\Credentials\FormBuilder\LegacyCredentialsFormBuilder'

  Mollie\Form\Admin\Credentials\LegacyCredentialsForm:
    class: Mollie\Form\Admin\Credentials\LegacyCredentialsForm
    arguments:
      - '@Mollie'

  Mollie\Form\Admin\Credentials\CredentialsFormInterface: '@Mollie\Form\Admin\Credentials\LegacyCredentialsForm'

  Mollie\Form\Admin\Credentials\CredentialsFormDataProvider:
    class: Mollie\Form\Admin\Credentials\CredentialsFormDataProvider
