imports:
  - { resource: ./form/form_builder.yml }
  - { resource: ./form/form_data_provider.yml }
  - { resource: ./form/form_type.yml }

services:
  Mollie\Service\LegacyTranslator:
    class: Mollie\Service\LegacyTranslator
    arguments:
      - '@mollie'

  Mollie\Form\Admin\Credentials\LegacyCredentialsForm:
    class: Mollie\Form\Admin\Credentials\LegacyCredentialsForm
    arguments:
      - '@Mollie'

  Mollie\Form\Admin\Credentials\CredentialsFormInterface: '@Mollie\Form\Admin\Credentials\LegacyCredentialsForm'

  Mollie\Form\Admin\GeneralSettings\LegacyGeneralSettingsForm:
    class: Mollie\Form\Admin\GeneralSettings\LegacyGeneralSettingsForm
    arguments:
      - '@Mollie'

  Mollie\Form\Admin\GeneralSettings\GeneralSettingsFormInterface: '@Mollie\Form\Admin\GeneralSettings\LegacyGeneralSettingsForm'
