services:
  Mollie\Provider\CreditCardLogoProvider:
    arguments:
      - '@=service("mollie.factory.module_factory").getLocalPath()'
      - '@=service("mollie.factory.module_factory").getPathUri()'

  Mollie\Service\PaymentMethod\PaymentMethodSortProvider:

  Mollie\Provider\PhoneNumberProvider:

  Mollie\Provider\PaymentOption\BasePaymentOptionProvider:
    class: Mollie\Provider\PaymentOption\BasePaymentOptionProvider
    arguments:
      - '@mollie'
      - '@=service("mollie.adapter.context")'
      - '@Mollie\Provider\CreditCardLogoProvider'
      - '@Mollie\Provider\PaymentFeeProvider'

  Mollie\Provider\PaymentOption\CreditCardPaymentOptionProvider:
    class: Mollie\Provider\PaymentOption\CreditCardPaymentOptionProvider
    arguments:
      - '@mollie'
      - '@=service("mollie.adapter.context")'
      - '@Mollie\Provider\CreditCardLogoProvider'
      - '@Mollie\Provider\OrderTotalProvider'
      - '@Mollie\Provider\PaymentFeeProvider'

  Mollie\Provider\PaymentOption\IdealPaymentOptionProvider:
    class: Mollie\Provider\PaymentOption\IdealPaymentOptionProvider
    arguments:
      - '@mollie'
      - '@=service("mollie.adapter.context")'
      - '@Mollie\Provider\CreditCardLogoProvider'
      - '@Mollie\Provider\PaymentFeeProvider'

  Mollie\Provider\PaymentFeeProvider:
    class: Mollie\Provider\PaymentFeeProvider
    arguments:
      - '@Mollie\Provider\OrderTotalProvider'