services:
  Mollie\Service\OrderFeeService:

  Mollie\Service\PaymentMethodService:
    arguments:
      - '@mollie'
      - '@Mollie\Repository\PaymentMethodRepository'
      - '@Mollie\Repository\MethodCountryRepository'
      - '@Mollie\Service\CartLinesService'
      - '@Mollie\Service\PaymentsTranslationService'
      - '@Mollie\Service\CustomerService'
      - '@Mollie\Provider\CreditCardLogoProvider'
      - '@Mollie\Service\PaymentMethod\PaymentMethodSortProvider'
      - '@Mollie\Provider\PhoneNumberProvider'
      - '@Mollie\Service\PaymentMethod\PaymentMethodRestrictionValidation'

  Mollie\Service\ApiService:
    arguments:
      - '@Mollie\Repository\PaymentMethodRepository'
      - '@Mollie\Repository\CountryRepository'
      - '@Mollie\Service\PaymentMethod\PaymentMethodSortProvider'
      - '@Mollie\Adapter\ConfigurationAdapter'
      - '@Mollie\Service\TransactionService'

  Mollie\Service\ConfigFieldService:
    arguments:
      - '@mollie'
      - '@Mollie\Service\ApiService'
      - '@Mollie\Repository\CountryRepository'

  Mollie\Service\IssuerService:
    arguments:
      - '@mollie'
      - '@Mollie\Repository\PaymentMethodRepository'

  Mollie\Service\RefundService:
    arguments:
      - '@mollie'
      - '@Mollie\Service\TransactionService'

  Mollie\Service\ShipService:
    arguments:
      - '@mollie'

  Mollie\Service\CancelService:
    arguments:
      - '@mollie'
      - '@Mollie\Service\TransactionService'

  Mollie\Service\CarrierService:

  Mollie\Service\OrderStatusService:
    arguments:
      - '@Mollie\Service\MailService'

  Mollie\Service\ErrorDisplayService:

  Mollie\Service\OrderStateImageService:

  Mollie\Service\CountryService:
    arguments:
      - '@mollie'

  Mollie\Service\SettingsSaveService:
    arguments:
      - '@mollie'
      - '@Mollie\Repository\CountryRepository'
      - '@Mollie\Repository\PaymentMethodRepository'
      - '@Mollie\Service\PaymentMethodService'
      - '@Mollie\Service\ApiService'
      - '@Mollie\Service\MolCarrierInformationService'
      - '@Mollie\Handler\Settings\PaymentMethodPositionHandlerInterface'
      - '@Mollie\Service\ApiKeyService'

  Mollie\Service\ShipmentService:
    arguments:
      - '@Mollie\Repository\OrderShipmentRepository'
      - '@Mollie\Repository\MolCarrierInformationRepository'

  Mollie\Service\CartLinesService:
    arguments:
      - '@Mollie\Service\LanguageService'
      - '@Mollie\Service\VoucherService'
      - '@Mollie\Adapter\ToolsAdapter'

  Mollie\Service\CustomerService:
    arguments:
      - '@mollie'
      - '@Mollie\Repository\MolCustomerRepository'

  Mollie\Service\MollieOrderInfoService:
    arguments:
      - '@mollie'
      - '@Mollie\Repository\PaymentMethodRepository'
      - '@Mollie\Service\RefundService'
      - '@Mollie\Service\ShipService'
      - '@Mollie\Service\CancelService'
      - '@Mollie\Service\ShipmentService'
      - '@Mollie\Service\ApiService'

  Mollie\Service\MolCarrierInformationService:
    arguments:
      - '@Mollie\Repository\MolCarrierInformationRepository'

  Mollie\Service\LanguageService:
    arguments:
      - '@mollie'

  Mollie\Service\CartDuplicationService:
    class: Mollie\Service\CartDuplicationService
    arguments:
      - '@Mollie\Service\CartRuleDuplicationService'
      - '@Mollie\Handler\CartRule\CartRuleQuantityResetHandler'

  Mollie\Service\CartRuleDuplicationService:
    class: Mollie\Service\CartRuleDuplicationService
    arguments:
      - '@Mollie\Repository\CartRuleRepository'

  Mollie\Service\OrderCartAssociationService:
    arguments:
      - '@Mollie\Service\CartDuplicationService'

  Mollie\Service\MemorizeCartService:
    arguments:
      - '@Mollie\Service\OrderCartAssociationService'
      - '@Mollie\Repository\PendingOrderCartRepository'

  Mollie\Service\RepeatOrderLinkFactory:

  Mollie\Logger\PrestaLogger:

  Psr\Log\LoggerInterface: '@Mollie\Logger\PrestaLogger'

  Mollie\Service\RestorePendingCartService:
    arguments:
      - '@Mollie\Repository\PendingOrderCartRepository'

  Mollie\Service\TransactionService:
    arguments:
      - '@mollie'
      - '@Mollie\Repository\PaymentMethodRepository'
      - '@Mollie\Service\OrderStatusService'

  Mollie\Service\MolliePaymentMailService:
    arguments:
      - '@mollie'
      - '@Mollie\Repository\PaymentMethodRepository'
      - '@Mollie\Service\MailService'

  Mollie\Service\MailService:
    arguments:
      - '@mollie'

  Mollie\Service\PaymentsTranslationService:
    - '@mollie'
    - '@Mollie\Service\LanguageService'

  Mollie\Service\PaymentReturnService:
    class: Mollie\Service\PaymentReturnService
    arguments:
      - '@mollie'
      - '@Mollie\Service\CartDuplicationService'
      - '@Mollie\Repository\PaymentMethodRepository'
      - '@Mollie\Service\RepeatOrderLinkFactory'
      - '@Mollie\Service\TransactionService'
      - '@Mollie\Handler\CartRule\CartRuleQuantityChangeHandler'

  Mollie\Service\UpgradeNoticeService:

  Mollie\Service\VoucherService:
    - '@Mollie\Repository\AttributeRepository'
    - '@Mollie\Adapter\ConfigurationAdapter'

  Mollie\Service\ExceptionService:
    - '@mollie'

  Mollie\Service\ApiKeyService:

  Mollie\Handler\CartRule\CartRuleQuantityChangeHandler:
    class: Mollie\Handler\CartRule\CartRuleQuantityChangeHandler
    arguments:
      - '@Mollie\Repository\PendingOrderCartRuleRepository'
      - '@Mollie\Repository\OrderCartRuleRepository'
      - '@Mollie\Repository\CartRuleRepository'
      - '@Mollie\Repository\OrderRepository'

  Mollie\Handler\CartRule\CartRuleQuantityResetHandler:
    class: Mollie\Handler\CartRule\CartRuleQuantityResetHandler
    arguments:
      - '@Mollie\Repository\PendingOrderCartRuleRepository'
      - '@Mollie\Repository\OrderCartRuleRepository'
      - '@Mollie\Repository\CartRuleRepository'
      - '@Mollie\Repository\OrderRepository'

  Mollie\Service\PaymentMethodOrderRestrictionUpdater:
    class: Mollie\Service\PaymentMethodOrderRestrictionUpdater
    arguments:
      - '@Mollie\Service\ApiService'

  Mollie\Service\OrderTotalService:
    class: Mollie\Service\OrderTotalService
    arguments:
      - '@=service("adapter.context")'
      - '@Mollie\Provider\OrderTotalRestrictionProvider'

  Mollie\Provider\OrderTotalProvider:
    class: Mollie\Provider\OrderTotalProvider
    arguments:
      - '@=service("adapter.context")'

  Mollie\Provider\OrderTotalRestrictionProvider:
    class: Mollie\Provider\OrderTotalRestrictionProvider
    arguments:


  Mollie\Provider\PaymentMethodCurrencyProvider:
    class: Mollie\Provider\PaymentMethodCurrencyProvider

  Mollie\Provider\PaymentMethodCountryProvider:
    class: Mollie\Provider\PaymentMethodCountryProvider
