name: Deploy

on:
  pull_request:
    types: [closed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: build
        run: |
          make bvn
          rm -rf .git
          rm -rf .github
          rm -rf vendorBuilder
          rm -rf node_modules
          rm -rf tests
          rm -rf views/js/node_modules
          rm -rf deploy
          rm -rf cypress
          rm -rf .docker
          mkdir mollie
          rsync -Rr ./ ./mollie
          shopt -s extglob
          rm -r !(mollie)
          find . -maxdepth 1 -type f -exec rm "{}" \;
          cd mollie && rm -rf mollie
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: mollie
          path: |
            .


